"""Initial schema

Revision ID: 3d7569818ac0
Revises:
Create Date: 2026-02-13 13:33:27.059375
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d7569818ac0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=128), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("items_affected", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_logs_job_name"), "job_logs", ["job_name"], unique=False)
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ebay_item_id", sa.String(length=64), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("title_sanitized", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("description_mobile", sa.Text(), nullable=True),
        sa.Column("brand", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("category_id", sa.String(length=32), nullable=True),
        sa.Column("condition_id", sa.String(length=16), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("list_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ad_rate_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("days_active", sa.Integer(), nullable=False),
        sa.Column("total_views", sa.Integer(), nullable=False),
        sa.Column("watchers", sa.Integer(), nullable=False),
        sa.Column("zombie_cycle_count", sa.Integer(), nullable=False),
        sa.Column("sell_through_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("str_data_source", sa.String(length=32), nullable=True),
        sa.Column("photo_urls_json", sa.Text(), nullable=True),
        sa.Column("main_photo_index", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.String(length=64), nullable=True),
        sa.Column("last_offer_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_repriced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listings_ebay_item_id"), "listings", ["ebay_item_id"], unique=True)
    op.create_index(op.f("ix_listings_sku"), "listings", ["sku"], unique=True)
    op.create_index(op.f("ix_listings_status"), "listings", ["status"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("ebay_campaign_id", sa.String(length=64), nullable=True),
        sa.Column("campaign_type", sa.String(length=32), nullable=False),
        sa.Column("ad_rate_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_listing_id"), "campaigns", ["listing_id"], unique=False)
    op.create_table(
        "listing_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("watchers", sa.Integer(), nullable=False),
        sa.Column("price_at_snapshot", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status_at_snapshot", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_snapshots_listing_id"), "listing_snapshots", ["listing_id"], unique=False
    )
    op.create_table(
        "offer_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.String(length=128), nullable=False),
        sa.Column("offer_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offer_records_buyer_id"), "offer_records", ["buyer_id"], unique=False)
    op.create_index(
        op.f("ix_offer_records_listing_id"), "offer_records", ["listing_id"], unique=False
    )
    op.create_table(
        "profit_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ebay_fee_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("ad_fee_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("ebay_fee_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ad_fee_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("net_profit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("profit_margin_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("meets_floor", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profit_records_listing_id"), "profit_records", ["listing_id"], unique=False
    )
    op.create_table(
        "queue_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("scheduled_window", sa.String(length=32), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_queue_entries_listing_id"), "queue_entries", ["listing_id"], unique=False
    )
    op.create_index(op.f("ix_queue_entries_status"), "queue_entries", ["status"], unique=False)
    op.create_table(
        "zombie_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("days_active_at_detection", sa.Integer(), nullable=False),
        sa.Column("views_at_detection", sa.Integer(), nullable=False),
        sa.Column("action_taken", sa.String(length=32), nullable=False),
        sa.Column("resurrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("old_item_id", sa.String(length=64), nullable=True),
        sa.Column("new_item_id", sa.String(length=64), nullable=True),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zombie_records_listing_id"), "zombie_records", ["listing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zombie_records_listing_id"), table_name="zombie_records")
    op.drop_table("zombie_records")
    op.drop_index(op.f("ix_queue_entries_status"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_listing_id"), table_name="queue_entries")
    op.drop_table("queue_entries")
    op.drop_index(op.f("ix_profit_records_listing_id"), table_name="profit_records")
    op.drop_table("profit_records")
    op.drop_index(op.f("ix_offer_records_listing_id"), table_name="offer_records")
    op.drop_index(op.f("ix_offer_records_buyer_id"), table_name="offer_records")
    op.drop_table("offer_records")
    op.drop_index(op.f("ix_listing_snapshots_listing_id"), table_name="listing_snapshots")
    op.drop_table("listing_snapshots")
    op.drop_index(op.f("ix_campaigns_listing_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_listings_status"), table_name="listings")
    op.drop_index(op.f("ix_listings_sku"), table_name="listings")
    op.drop_index(op.f("ix_listings_ebay_item_id"), table_name="listings")
    op.drop_table("listings")
    op.drop_index(op.f("ix_job_logs_job_name"), table_name="job_logs")
    op.drop_table("job_logs")
    # ### end Alembic commands ###
